spring:
  application:
    name: DATADISPLAY

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://106.15.104.64:3306/frog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: _gA7Ca%a0HP
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  type-aliases-package: org.wpp.frogdata.datadisplay.model    # 所有model别名类所在包
  mapper-locations: mybatis/**/*Mapper.xml

#日志级别
logging:
  level:
    root: info
    org.wpp: debug